"""add prompt version

Revision ID: 2df2170acab9
Revises: b431fe80cc97
Create Date: 2025-05-24 10:27:24.635251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df2170acab9'
down_revision = 'b431fe80cc97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompt_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'prompt_version')
    # ### end Alembic commands ###
