"""add stream_data column to Activity

Revision ID: 85ab3d6b2278
Revises: 8eee071892cc
Create Date: 2025-08-09 14:44:05.946412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ab3d6b2278'
down_revision = '8eee071892cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('stream_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'stream_data')
    # ### end Alembic commands ###
