"""add default naming strategy

Revision ID: 8eee071892cc
Revises: babcdc60e701
Create Date: 2025-05-27 15:50:10.607945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eee071892cc'
down_revision = 'babcdc60e701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'naming_strategy_version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='v2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'naming_strategy_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
