"""current state

Revision ID: b431fe80cc97
Revises: c6d9e56ecb17
Create Date: 2025-05-24 10:25:03.795750

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "b431fe80cc97"
down_revision = "c6d9e56ecb17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "activity", "user", ["athlete_id"], ["athlete_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "activity", type_="foreignkey")
    # ### end Alembic commands ###
