"""add user type

Revision ID: babcdc60e701
Revises: c924600b4e9c
Create Date: 2025-05-27 15:16:12.834567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babcdc60e701'
down_revision = 'c924600b4e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.String(), nullable=False, server_default='neuraltag'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
