"""rename prompt version column

Revision ID: c924600b4e9c
Revises: 2df2170acab9
Create Date: 2025-05-24 10:58:06.605418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c924600b4e9c'
down_revision = '2df2170acab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('naming_strategy_version', sa.String(), nullable=True))
    op.drop_column('user', 'prompt_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'naming_strategy_version')
    # ### end Alembic commands ###
