services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5433:5432
  strava:
    environment:
      - APPLICATION_URL=http://localhost
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PUSHBULLET_API_KEY=${PUSHBULLET_API_KEY}
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/postgres
      - STRAVA_VERIFY_TOKEN=${STRAVA_VERIFY_TOKEN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    depends_on:
      - postgres
    command: ["fastapi", "run", "src/app/main.py", "--host", "0.0.0.0", "--port", "8000"]
