services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5433:5432
  strava:
    build:
      context: .
      dockerfile: ./cicd/rpi_deploy/Dockerfile
    environment:
      - APPLICATION_URL=http://localhost
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PUSHBULLET_API_KEY=${PUSHBULLET_API_KEY}
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/postgres
      - STRAVA_VERIFY_TOKEN=${STRAVA_VERIFY_TOKEN}
    image: ghcr.io/niklasvm/strava:latest
    depends_on:
      - postgres
    command: ["fastapi", "run", "src/app/main.py", "--host", "0.0.0.0", "--port", "8000"]
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./cicd/rpi_deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      # - certs:/etc/letsencrypt
    restart: always
    depends_on:
      - strava
# volumes:
#   certs:
