name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Login
      run: |

        gcloud auth configure-docker ${{secrets.GCP_REGION}}-docker.pkg.dev
    

    - name: Build and push the Docker image
      run: |
        docker build -t ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:latest .
        docker push ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:latest