name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup dependencies
      run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip compile pyproject.toml -o requirements.txt
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7