name: Deploy application to Google Cloud Platform

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:

  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      run: terraform -chdir=terraform init
    - name: Terraform Validate
      run: terraform -chdir=terraform validate
    
    - name: Login
      run: |
        gcloud auth configure-docker ${{secrets.GCP_REGION}}-docker.pkg.dev
    
    # deploy docker image
    - name: Build and push the Docker image
      run: |
        docker build -t ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:${{github.sha}} .
        docker push ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:${{github.sha}}    
    
    - name: Terraform Plan
      run: |
        terraform -chdir=terraform plan \
          -var "gcp_project_id=${{secrets.GCP_PROJECT_ID}}" \
          -var "gcp_sa_key=${{secrets.GCP_SA_KEY}}" \
          -var "gcp_region=${{secrets.GCP_REGION}}" \
          -var "image_tag=${{ github.sha }}"
    - name: Terraform Apply
      run: |
        terraform -chdir=terraform apply -auto-approve \
          -var "gcp_project_id=${{secrets.GCP_PROJECT_ID}}" \
          -var "gcp_sa_key=${{secrets.GCP_SA_KEY}}" \
          -var "gcp_region=${{secrets.GCP_REGION}}" \
          -var "image_tag=${{ github.sha }}"

    - name: Delete all docker images except latest one
      run: |
        gcloud container images list-tags ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava \
          --filter='tags!=${{ github.sha }}' \
          --format='get(digest)' \
          | xargs -I {} gcloud container images delete ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava@{} --force-delete-tags
    - name: Delete old Google Cloud Run revisions
      run: |
        TO_DELETE=$(gcloud run revisions list --region=${{secrets.GCP_REGION}} --service=strava \
          --filter="status.conditions.type:Active AND status.conditions.status:'False'" \
          --format='value(metadata.name)')
        if [ -n "$TO_DELETE" ]; then
            for REVISION in $TO_DELETE; do
                gcloud run revisions delete $REVISION --region=${{secrets.GCP_REGION}} --quiet
            done
        fi
    