name: Build and Push Docker Image

on:
  pull_request:
    branches: [ master ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and push the Docker image
      run: |
        docker build -t ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:v2 .
        docker push ${{secrets.GCP_REGION}}-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/strava/strava:v2
        