name: PR Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: PR Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv sync
      
      - name: Run lint tests
        run: |
            source .venv/bin/activate
            make lint_tests
      
      - name: Run unit tests
        run: |
            source .venv/bin/activate
            make unit_tests

      - name: Add coverage to PR
        id: jacoco
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_only:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Build the Docker image
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          docker build . -t ghcr.io/${{ github.repository }}:latest

  docker_build_armv7:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Build the Docker image for ARMv7
        run: |
          uv run python cicd/deploy/modify_pyproject_toml.py
          docker build . -t ghcr.io/${{ github.repository }}:armv7 --build-arg BASE_IMAGE=arm32v7/python:3.11-slim-bookworm