name: Update Strava Activity Names

on:
  # schedule:
  #   # Runs every hour between 8am and 6pm UTC (9am and 7pm CEST)
  #   - cron: '*/15 6-18 * * *'
  workflow_dispatch: {
    inputs: {
      activity_id: {
        description: 'Activity ID to update',
        required: true,
      }
    }
  }
  # push:
  #   branches:
  #     - master

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv sync

      - name: Run script
        run: |
          source .venv/bin/activate
          python src/workflows.py --activity_id ${{ github.event.inputs.activity_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STRAVA_TOKEN: ${{ secrets.STRAVA_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
