name: Update Strava Activity Names

on:
  schedule:
    # Runs every hour between 8am and 6pm UTC (9am and 7pm CEST)
    - cron: '0 6-16 * * *'
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install . --system

      - name: Run script
        run: python src/naming.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STRAVA_TOKEN: ${{ secrets.STRAVA_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}

      
      - name: Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Automated update by GitHub Actions"
          git remote set-url --push origin https://git:$GITHUB_TOKEN@github.com/niklasvm/strava
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
